import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const ENV_PATH = join(process.cwd(), ".env");

export const DEFAULT_SCOPES = [
  "profile",
  "backoffice:shop:read",
  "backoffice:shop:write",
  "backoffice:business-profile:read",
  "backoffice:business-profile:write",
  "backoffice:company:read",
  "backoffice:company:write",
  "backoffice:product:read",
  "backoffice:product:write",
  "backoffice:category:read",
  "backoffice:category:write",
  "backoffice:property-set:read",
  "backoffice:property-set:write",
  "backoffice:order:read",
  "backoffice:order:write",
  "backoffice:report:read",
  "backoffice:customer:read",
  "backoffice:customer:write",
  "backoffice:reviews:read",
  "backoffice:reviews:write",
  "backoffice:community:read",
  "backoffice:community:write",
  "backoffice:logistic:read",
  "backoffice:logistic:write",
  "backoffice:print:read",
  "backoffice:print:write",
  "backoffice:finance:read",
  "backoffice:finance:write",
  "backoffice:giftcard:read",
  "backoffice:giftcard:write",
  "backoffice:vendor-payment:read",
  "backoffice:vendor-payment:write",
  "backoffice:discount-code:read",
  "backoffice:discount-code:write",
  "backoffice:coupon:read",
  "backoffice:coupon:write",
  "backoffice:offer:read",
  "backoffice:offer:write",
  "backoffice:cashback:read",
  "backoffice:cashback:write",
  "backoffice:lottery:read",
  "backoffice:lottery:write",
  "backoffice:ribbon:read",
  "backoffice:ribbon:write",
  "backoffice:affiliate:read",
  "backoffice:affiliate:write",
  "backoffice:page:read",
  "backoffice:page:write",
  "backoffice:faq:read",
  "backoffice:faq:write",
  "backoffice:ai:read",
  "backoffice:ai:write",
  "articles",
  "backoffice:notifications",
  "backoffice:support-tickets",
  "backoffice:staff:read",
  "backoffice:staff:write",
  "backoffice:note:read",
  "backoffice:note:write",
  "connect:provider:read",
  "connect:provider:write",
  "vendor-read",
  "vendor-write",
  "agency:read",
  "agency:write",
  "selldone:developer:read",
  "selldone:developer:write",
  "selldone:monetization:read",
  "selldone:monetization:write",
];

export const DEFAULT_STOREFRONT_SCOPES = [
  "profile",
  "phone",
  "address",
  "user:profile:write",
  "buy",
  "order-history",
  "my-gift-cards",
];

const STOREFRONT_SCOPE_SET = new Set(DEFAULT_STOREFRONT_SCOPES);

export const DEFAULT_ENV = {
  SETUP_COMPLETE: "false",
  PORT: "5173",
  APP_NAME: "Pajulina Local Operations Dashboard",
  APP_BASE_URL: "http://localhost:5173",
  DASHBOARD_PATH: "/dashboard/",
  CALLBACK_PATH: "/callback",
  SELLDONE_BASE: "https://selldone.com",
  API_BASE: "https://api.selldone.com",
  STOREFRONT_XAPI_BASE: "https://xapi.selldone.com",
  AUTH_PROMPT: "consent",
  CLIENT_ID: "019e9c01-9f93-7165-a48c-6a4942c9c248",
  SHOP_ID: "14952",
  SHOP_NAME: "Pajulina",
  SHOP_DOMAIN: "https://pajulina.myselldone.com",
  STOREFRONT_SHOP_HANDLE: "pajulina",
  STOREFRONT_SCOPES: DEFAULT_STOREFRONT_SCOPES.join(","),
  SCOPES: DEFAULT_SCOPES.join(","),
};

const ENV_KEYS = Object.keys(DEFAULT_ENV);

export function parseEnvText(text = "") {
  const env = {};
  text.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) return;
    const [, key, rawValue] = match;
    env[key] = unquoteEnvValue(rawValue);
  });
  return env;
}

export function readEnvFile() {
  if (!existsSync(ENV_PATH)) return {};
  return parseEnvText(readFileSync(ENV_PATH, "utf8"));
}

export function loadEnvFile() {
  const fileEnv = readEnvFile();
  Object.entries(fileEnv).forEach(([key, value]) => {
    if (process.env[key] === undefined) process.env[key] = value;
  });
  return fileEnv;
}

export function getRuntimeConfig() {
  const fileEnv = readEnvFile();
  const merged = { ...DEFAULT_ENV, ...fileEnv };
  ENV_KEYS.forEach((key) => {
    if (process.env[key] !== undefined) merged[key] = process.env[key];
  });

  return {
    ...merged,
    setupComplete: merged.SETUP_COMPLETE === "true",
    port: toInteger(merged.PORT, 5173),
    shopId: toInteger(merged.SHOP_ID, 0),
    scopes: splitScopes(merged.SCOPES),
    storefrontScopes: normalizeStorefrontScopes(merged.STOREFRONT_SCOPES),
  };
}

export function isSetupComplete() {
  const config = getRuntimeConfig();
  return Boolean(config.setupComplete && config.CLIENT_ID && config.shopId);
}

export function saveSetupEnv(updates = {}) {
  const current = { ...DEFAULT_ENV, ...readEnvFile() };
  const next = {
    ...current,
    ...normalizeSetupUpdates(updates),
    SETUP_COMPLETE: "true",
  };
  writeEnvFile(next);
  Object.entries(next).forEach(([key, value]) => {
    process.env[key] = String(value);
  });
  return getRuntimeConfig();
}

export function writeEnvFile(values) {
  const lines = [
    "# Pajulina Selldone Shop local setup",
    "# Generated by /setup. Do not store access tokens here.",
    "",
    ...ENV_KEYS.map((key) => `${key}=${formatEnvValue(values[key] ?? DEFAULT_ENV[key] ?? "")}`),
    "",
  ];
  writeFileSync(ENV_PATH, lines.join("\n"), "utf8");
}

function normalizeSetupUpdates(updates) {
  const normalized = {};
  Object.entries(updates || {}).forEach(([key, value]) => {
    if (!ENV_KEYS.includes(key)) return;
    if (value === undefined || value === null) return;
    if (Array.isArray(value)) normalized[key] = value.join(",");
    else normalized[key] = String(value ?? "").trim();
  });
  return normalized;
}

function splitScopes(value) {
  return String(value || "")
    .split(/[,\s]+/)
    .map((scope) => scope.trim())
    .filter(Boolean);
}

function normalizeStorefrontScopes(value) {
  const requestedScopes = splitScopes(value).filter((scope) => STOREFRONT_SCOPE_SET.has(scope));
  return Array.from(new Set([...DEFAULT_STOREFRONT_SCOPES, ...requestedScopes]));
}

function toInteger(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function unquoteEnvValue(value) {
  const trimmed = String(value || "").trim();
  if (!trimmed) return "";
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1).replaceAll("\\n", "\n").replaceAll('\\"', '"');
  }
  return trimmed.replace(/\s+#.*$/, "");
}

function formatEnvValue(value) {
  const text = String(value ?? "");
  if (!text || /[\s#"'\\]/.test(text)) return JSON.stringify(text);
  return text;
}
